### ISSUE TITLE
Current Sample Json file does not include "Cartridges" field 

### ISSUE THREAD

**Issue by dmueller2001** [openshift/oo-index#10]
the sample json file (https://github.com/openshift/oo-index/blob/master/quickstart.json) is missing the field 'cartridges' with the cartridges used for each item. This is in the annotated G+ spreadsheet, so perhaps ryan could regenerate the json file to include this one so we have a valid sample

**Comment by ryanj** [comment]
I think this is completed. Please reopen if it still needs to be fixed.
