### ISSUE TITLE
Mock-ups of UX for Adding New Items to the Index

### ISSUE THREAD

**Issue by dmueller2001** [openshift/oo-index#11]
Workflow for Adding a New Item to the Index via form:
![image](https://f.cloud.github.com/assets/4029488/1946129/cdf93b1a-7fec-11e3-87b5-1370b1aaae0e.png)

Success/Thank You Window and further notes:
![image](https://f.cloud.github.com/assets/4029488/1946131/f3297350-7fec-11e3-9da0-4b74148fece3.png)

**Comment by dmueller2001** [comment]
when there's an 'OR' on which cartridges are being used - aka which one should be used to populate the console

**Comment by dmueller2001** [comment]
http://ivaynberg.github.io/select2/#tags - use of tags here as a possible solution

**Comment by caruccio** [comment]
Do we really need a "signup" button?
AFAIK, any existing github user is a potential user of oo-index, thus, he/she does not need to signup for oo-index, but simply does a signin.
