### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by dmueller2001** [openshift/oo-index#15]
Something to think about is creating a 'resource' file for all the strings in the UI so that the application can be easily localized. To respect the fact, that GetUpCloud will more than likely be doing a Brazilian/Portuguese version of the index, I am wondering if there is a simple way of doing this in the MVP. Ideas/Thoughts? Does this introduce a level of complexity that is burdensome for the MVP?

**Comment by caruccio** [comment]
I'd like to suggest we use gettext translation format, PO.
I's pretty standard and easy to handle in case we choose to switch to another translation mechanism.

http://www.gnu.org/software/gettext/manual/gettext.html#PO-Files

There is a node-gettext implementation. There is even a javascript version of gettext (http://jsgettext.berlios.de)

**Comment by Nagib** [comment]
With the gettext, suggestion of Mateus, we can use the angular-gettext (https://github.com/rubenv/angular-gettext) to implement the internationalization in client-side application.

**Comment by dmueller2001** [comment]
I knew there would be a simple solution, thanks guys
