### ISSUE TITLE
Sorting quickstart.json 

### ISSUE THREAD

**Issue by caruccio** [openshift/oo-index#16]
Should we keep `quickstart.json` sorted to try to minimize conflicts when PRs arrive?

**Comment by mignev** [comment]
Hello @caruccio i have an idea about that. To prevent these kind of conflicts, what do you think to change the logic a little bit. Let's say to collect all the quickstarts and cartridges examples in separate directory as separate json files. We have to  think of a convention for the names of files. 
For example:
`<package-name>_<author>_<type>.json`

Which can be represented as in my case as a quickstart developer ...:
`jekyll_mignev_quickstart.json`

or in case that the developer is you:
`minecraft_caruccio_quickstart.json` or `flask-mysql_caruccio_quickstart.json`

Another approach can be the following. Every author will make own file for example `mignev.json` and there he will push all the quickstarts and cartridges that are made by himself.

And when the `oo-index` is deployed to the servers there in the `build` step of the deploying process we can concatenate all the quickstarts and cartridges in one quickstart.json file.

This will resolve the problem with merges i think and will make us happy :)

What do you think?

**Comment by dmueller2001** [comment]
mignev: my thought was to have a periodic cron job setup to do the following (sort the json file, update the github stats fields - "Stars", "Most Recent Updates", and "Popular"); this would run nightly or whenever the "admin" for the app kicked it off.

**Comment by mignev** [comment]
@dmueller2001 i got it! But i think if we separate quickstarts in some of ways that i mentioned above, there wasn't be a problem to run cron jobs on the server as well. :) The files that cron will generate will be only in the server in some `$OPENSHIFT_DATA_DIR/cache` directory and i think this will be fine for us :)
