### ISSUE TITLE
Premature thoughts

### ISSUE THREAD

**Issue by caruccio** [openshift/oo-index#3]
Just as an exercise, here are some of my impressions of what may be driving this project (Please note this is not an MVP).
### Many cartridge sources (github, DB, local file/dir...)

JSON file is cool, but many different sources is cooler! It would be amazing if I could configure oo-index to drain cartridge metadata from many sources as github public repos (maybe a plain search), some sql/nosql databases, local file (is this the initial json file we are talking about?), some local dir (a.k.a. /var/lib/openshift/.cartridge_repository/), etc...
### API

I see this project not as a simple "index",  but rather as a media to get a list of cartridges/quickstarts from a centralized place. That said, it could be able to export that content in a more standard way other than a web app (we are tied to a web browser here).
### Themeable

Everybody loves to play with themes! in fact this is the very first thing I do after signup to a new service :P

Moreover, theming is an essencial key for adoption by other players and vendors.
### Cart Suggestions/Depends

Users of a service often get lost and don't known where to go next. How about suggesting "hey, why don't you add some cache to your app since it already have php and mysql installed"?
### README.md description

This is more like a patch than a feature: cartridge/quickstart developers will need to actively insert metadata to their repositories. For now, we could simply present repository's README.md file since this is the default source of information for users of a given cartridge.

**Comment by ryanj** [comment]
Great feedback!   I'd love to offer an API, and the means to update existing data - or even to replicate data from an official source (from GitHub, or from a centralized and officially maintained index).
Our initial iteration will likely load up it's default content from a local JSON file.  

I've documented some initial contribution guidelines (which mostly focus on data rather than UI enhancements).

**Comment by dmueller2001** [comment]
Please keep in mind that this a _Minimal Viable Proto-type_  (MVP) - the initial use of the json file for storage is understandably not optimal .  Initially the MVP, this will be deployed on openshift online and linked to the http://openshift.github.io community pages. The idea is to create a community forge-like experience and get feedback on the UX and workflow for adding new cartridges & quick starts from the community. 

The bonus of using the standalone angularjs approach is that anyone could host and re-theme their own index too.

**Comment by caruccio** [comment]
Sure, I just dropped it here to avoid losing it.
