### ISSUE TITLE
asset management

### ISSUE THREAD

**Issue by EmilyDirsh** [openshift/oo-index#39]
This project really could use some asset management, and I thought an issue would be the best way to bring it up for discussion. 

I ran into this when adding the new css for the footer. Having all the css files concatted and minified is great for production sites, but a huge pain for development. Likewise for javascript.

I'm not super familiar with python web development, but some quick googling turned up [web-assets]([http://flask-assets.readthedocs.org/en/latest/) and [flask funnel](https://github.com/rehandalal/flask-funnel).

I'm happy to work on integrating a solution, but given the aforementioned lack of familiarity, I'm not sure which one is better, or even if there are other _even better_ solutions that aren't showing up on google for some reason.

**Comment by dmueller2001** [comment]
so far, I have just been putting all the assets in to this folder 

https://github.com/openshift/oo-index/tree/master/wsgi/static/img

**Comment by dmueller2001** [comment]
Mateus added the flask funnel - Emily could you let us know if that is going to work for you or if you need further information on how to use it?

**Comment by caruccio** [comment]
Just to clarify, this is what you need to do to locally rebuild the assets:

First, install any nodejs requirements:

```
npm install uglify-js
npm install clean-css
```

Once installed, rebuild it by running:

```
python manage.py funnel bundle_assets
```

Run your dev-env with:

```
DEBUG=0 ./start-devel.sh [GITHUB_CLIENT_ID] [GITHUB_CLIENT_SECRET]
```
