### ISSUE TITLE
Workflow for adding new cartridges & quickstarts to index

### ISSUE THREAD

**Issue by dmueller2001** [openshift/oo-index#5]
Currently the json file lives in the oo-index repo, in the readme.md file there is a suggestion that if someone adds a snippet of json to their existing repo and submits a pull request - that magically it will get added to the 'canonical' json file and become part of the community index.

There are a couple of issues with this approach. 

(a) When oo-index is deployed to openshift online, the json file that was pushed at deployment time is the one that needs to be updated in order for the new item to appear in the community index.  A pull request would make an update to the repo in github but not the repo of the deployed app on openshift online. 

(b) authentication via github account, minimal barrier that put the burden of managing authentication on github. in order to submit a new item to the index, the submitter must be logged into github and (magically) submit a new item & it's details that triggers a pull request associated with that user's github account to update the json file in openshift/oo-index repo.

**Comment by caruccio** [comment]
For (a), how about a checkbox "load from github" ?
Maybe always loading from 'canonical' location (i.e. same location as oo-index is hosted) followed by a data merge/update from github (also optional).

For (b) maybe it would be less erro prone if someone review before accept PRs.
