### ISSUE TITLE
Provide a way to export Quickstart json for inclusion into OSO local deployment.

### ISSUE THREAD

**Issue by sferich888** [openshift/oo-index#77]
It would be nice to see a button or link that allows me to export 1 or a list of quickstarts in json format for inclusion into my /etc/openshift/quickstarts.json file of my OpenShift Origin  Install.

**Comment by caruccio** [comment]
Hi. You can read this file from http://origin.ly/static/quickstart.json

**Comment by sferich888** [comment]
@caruccio thats a cool link (and it has the content I'm looking for) but that simply gives me the full list of what the index provides. It's also not user friendly. 

What if I only wanted 2 of those cartridges, (that's a lot to delete, and error prone). Having something get auto generated based on selections seems like a better user experience.

**Comment by sosiouxme** [comment]
Also since the app already has the logic for generating the .json... would be nice if someone could generate it for an app _without_ submitting to the index (to use in their own deployment).

**Comment by caruccio** [comment]
@sferich888 Now I get it :) Will ask @dmueller2001 to tag this issue as "feature request".

@sosiouxme In fact, the file is not generated on the fly. The app updates the file from github, and then it is synced into the app's gear using a cron job. A user cloning this repo will have an updated version already, and you can always host your own OO-Index. (Did I understood your suggestion?)

**Comment by dmueller2001** [comment]
That's a great feature request from @sferich888 - I could see a landing page that had a list of all the quickstarts and cartridges that had 'checkboxes' to select which ones that the user wanted to include in their export - @sferich888 - would that be what you had in mind? and if so, how about doing a little community coding ;-)

**Comment by sferich888** [comment]
@dmueller2001 Yea that's kinda the idea I had in mind. I'll see if I have time to do a pull request.
